---
- hosts: all
  remote_user: root
  become: yes
  gather_facts: no

  vars_prompt:
  - name: selection
    prompt: |
      Veuillez sélectionner votre choix :
      1 - NTP
      2 - SWAP (en cours de création)
      3 - FS (en cours de création)
    private: no
   
  roles:
    - role: shiftleft
